version: "3.9"
   
services:
  challenge-db:
    image: postgres
    container_name: challenge-db
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - "5432"
    networks: 
      - challenge_network
      
  challenge-api:
    build: .
    container_name: challenge-api
    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - challenge-db
    networks: 
      - challenge_network

networks:
  challenge_network:
    name: challenge_network
    driver: bridge
  